<?php



// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return [
    'TranslatedException\\' => [$vendorDir.'/coldume/translated-exception/src'],
    'Symfony\\Polyfill\\Mbstring\\' => [$vendorDir.'/symfony/polyfill-mbstring'],
    'Symfony\\Polyfill\\Ctype\\' => [$vendorDir.'/symfony/polyfill-ctype'],
    'Symfony\\Component\\Translation\\' => [$vendorDir.'/symfony/translation'],
    'Symfony\\Component\\Filesystem\\' => [$vendorDir.'/symfony/filesystem'],
    'Symfony\\Component\\EventDispatcher\\' => [$vendorDir.'/symfony/event-dispatcher'],
    'Symfony\\Component\\Config\\' => [$vendorDir.'/symfony/config'],
    'ImcStream\\' => [$vendorDir.'/coldume/imc-stream/src'],
    'Imagecraft\\' => [$vendorDir.'/coldume/imagecraft/src'],
];
