<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitb7e41719e061d05234f1d2e4939fb7ee
{
    public static $fallbackDirsPsr4 = array (
        0 => __DIR__ . '/..' . '/league/color-extractor/src',
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->fallbackDirsPsr4 = ComposerStaticInitb7e41719e061d05234f1d2e4939fb7ee::$fallbackDirsPsr4;
            $loader->classMap = ComposerStaticInitb7e41719e061d05234f1d2e4939fb7ee::$classMap;

        }, null, ClassLoader::class);
    }
}
